[prune]
  go-tests = true
  unused-packages = true
 
 [metadata.heroku]
  root-package = "github.com/adammillerio/cloudyn"
  go-version = "1.11"

[[constraint]]
  name = "github.com/cloudflare/cloudflare-go"
  version = "0.8.5"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.1.1"

[[constraint]]
  name = "github.com/kelseyhightower/envconfig"
  version = "1.3.0"
